#ifndef _H_ERRORS__
#define _H_ERRORS__

#define ERROR_MEM_ALLOC				0x01
#define ERROR_MEM_CLEANUP			0x02
#define ERROR_MEMCPY_DEVICE_HOST	0x03

#define ERR_MEM_ALLOC				0x04
#define ERR_MEM_FREE					0x05

#define ERROR_MEMCPY_TRAINSETX	0x06
#define ERROR_MEMCPY_TESTSETX		0x07
#define ERROR_MEMCPY_TRAINSETY 	0x08
#define ERROR_MEMCPY_TESTSETY 	0x09

#define ERROR_DEBUG					0x10
#define ERROR_MEMSET					0x11

#define ERROR_MEMCPY_DEVICE_DEVICE	0x13
#define ERROR_MEMCPY_HOST_DEVICE	0x14

#endif
