#!/bin/bash


mv 500_ms_alexnet_cifar_none_swish_maxpadpool_1.log 500_ms_alexnet_cifar_none_softplus_maxpadpool_1.log
mv 500_ms_alexnet_cifar_none_swish_maxpadpool_2.log 500_ms_alexnet_cifar_none_softplus_maxpadpool_2.log
mv 500_ms_alexnet_cifar_none_swish_maxpadpool_3.log 500_ms_alexnet_cifar_none_softplus_maxpadpool_3.log
mv 500_ms_alexnet_cifar_none_swish_maxpadpool_4.log 500_ms_alexnet_cifar_none_softplus_maxpadpool_4.log
mv 500_ms_alexnet_cifar_none_swish_maxpadpool_5.log 500_ms_alexnet_cifar_none_softplus_maxpadpool_5.log
mv 500_ms_alexnet_cifar_none_swish_maxpadpool_6.log 500_ms_alexnet_cifar_none_softplus_maxpadpool_6.log
mv 500_ms_alexnet_cifar_none_swish_maxpadpool_7.log 500_ms_alexnet_cifar_none_softplus_maxpadpool_7.log
mv 500_ms_alexnet_cifar_none_swish_maxpadpool_8.log 500_ms_alexnet_cifar_none_softplus_maxpadpool_8.log
mv 500_ms_alexnet_cifar_none_swish_maxpadpool_9.log 500_ms_alexnet_cifar_none_softplus_maxpadpool_9.log
mv 500_ms_alexnet_cifar_none_swish_maxpadpool_10.log 500_ms_alexnet_cifar_none_softplus_maxpadpool_10.log
